# Project information
site_name: VERO Research
site_url: https://veroresearch.org/
site_author: VERO Research
site_description: VERO Research

# Copyright
copyright: '&copy; VERO Research'

# Footer mod: https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#generator-notice 
extra:
  generator: false
  social:
    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/tamuvetmedVERO/

# Configuration
theme:
  name: material
  custom_dir: overrides
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    logo: vero-logo
    custom:
      - path: overrides/.icons/vero-logo.svg
        id: vero-logo
  favicon: assets/vero-logo.png #browser tab logo
  disable_navigation: true # add this line to disable navigation arrows
  material:
    pagination:
      enabled: false

#Plugins
plugins:
   - search
   - glightbox:
       touchNavigation: true
       loop: true
       effect: zoom
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes: 
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom

# Custom theme additions
extra_css:
  - stylesheets/extra.css

# Custom javascript
extra_javascript:
  - javascripts/extra.js

# Extensions
markdown_extensions:
  - tables
  - footnotes
  - admonition
  - attr_list
  - md_in_html
  - abbr
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Page Tree
nav:
  - Home: index.md
  - Who We Are: whoweare.md
  - Contact: contact.md
  - People: people.md
  - Current Research: research.md
  - News: news.md
  - Outreach: outreach.md
  - Published Research: pubs.md
  - Resources: 
      - Resources: resources.md
      - VERO faculty: pipages.md
      - Morley lab: people/morley.md
      - Pinell lab: people/pinnell.md
      - Scott lab: people/scott.md
      - Valeris lab: people/valeris.md